language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t marekkowalonek/docker2 -f Dockerfile.dev .

script:
  - docker run -e CI=true marekkowalonek/docker2 npm run test -- --coverage
