language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t marekkowalonek/docker2 -f Dockerfile.dev .

script:
  - docker run -e CI=true marekkowalonek/docker2 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker2"
  env: "Docker2-env"
  bucket_name: "elasticbeanstalk-us-east-1-311818010452"
  bucket_path: "docker2"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY